### ISSUE TITLE
Different results from same pyproject.toml file

### ISSUE THREAD

**Issue by levsa** [urm8/IsortConnect#1]
Thanks for a nice plugin! It will be really useful.

With these pyproject.toml settings, I get different results when ISortConnect plugin sorts the imports vs if I run `isort` manually:

```
[tool.isort]
profile = 'black'
line_length = 100
ensure_newline_before_comments = true
default_section = 'THIRDPARTY'
known_first_party = 'mycompany'
order_by_type = false
case_sensitive = false
force_single_line = true
```

**Comment by urm8** [comment]
Hello, @levsa! Could you please provide more detailed example ? 
For now the only thing I could find is that config differs in src paths.
```
{
    "values_changed": {
        "root['sources'][2]['source']": {
            "new_value": "C:\\Users\\mm\\AppData\\Local\\Temp\\pyproject.toml",
            "old_value": "C:\\Users\\mm\\Documents\\github.com\\urm8\\isortd\\pyproject.toml"
        },
        "root['directory']": {
            "new_value": "C:\\Users\\mm\\AppData\\Local\\Temp",
            "old_value": "C:\\Users\\mm\\Documents\\github.com\\urm8\\isortd"
        },
        "root['src_paths'][0]": {
            "new_value": "C:\\Users\\mm\\AppData\\Local\\Temp\\src",
            "old_value": "C:\\Users\\mm\\Documents\\github.com\\urm8\\isortd\\src"
        },
        "root['src_paths'][1]": {
            "new_value": "C:\\Users\\mm\\AppData\\Local\\Temp",
            "old_value": "C:\\Users\\mm\\Documents\\github.com\\urm8\\isortd"
        }
    }
}
```
isort tool tries to guess the src paths when started from cli, so if this is your case and only your local imports get messed up, then I'll try to push fix for that in next few days

**Comment by levsa** [comment]
I'll try to run a more detailed test soon.

In the meantime, I tried to do some fixes. I'm not sure if I'm correct, but it looked like the plugin didn't handle all the files in the events but just the first. When I fixed that, I managed to get a lot of files have their imports sorted although I hadn't touched them, so I added a check for modification too. Please check and see if there is anything useful and feel free to use it. Or let me know if I should create a pull request: 

https://github.com/levsa/IsortConnect/tree/fix/code_style_and_multiple_file_update

The branch is made from the release/2020.3 tag.

By the way, when I tested my changes, first none of the settings from the `pyproject.toml` applied. Until I cleared the `pyproject.toml` path in the settings and clicked `Apply` and put it back and clicked `Apply` again. Can it be an issue with when the settings are reread?

**Comment by urm8** [comment]
Yeah, pyproject.toml changes not always detected by listener for some reason, mb that is the same case, that you handled in your branch (only first file in change event handled), but if you make changes to it, they should be applied at some point (try spam return + backspace). Will try to handle that when I have free weekend :)
I viewed your changes and ported them to the new release

**Comment by levsa** [comment]
Just installed the new version of the plugin, thanks for the quick release!

**Comment by urm8** [comment]
Hi @levsa  is problem fixed for you ?
